export const FORM_FIELD_NAME = {
  LINK: "link",
  NAME: "name",
};

export const ICON_NAME = {
  MAGNIFIER: "ICON_NAME__MAGNIFIER",
  PLUS_IN_CIRCLE: "ICON_NAME__PLUS_IN_CIRCLE",
  TRASH: "ICON_NAME__TRASH",
  TWO_CROSSED_DOUBLE_ARROWS: "ICON_NAME__TWO_CROSSED_DOUBLE_ARROWS",
};
